drop index if exists IDX_RATING_IID;
drop index if exists IDX_TITLE_IID;
drop index if exists IDX_RATING_IID_UID;
drop index if exists IDX_RATING_SUID_TUID;
drop index if exists IDX_NAME_UID;
drop index if exists IDX_MVIEW_GARBTU;
drop index if exists IDX_MVIEW_GIRBTU;
drop index if exists IDX_MVIEW_GRIBI;
drop index if exists IDX_MVIEW_GRBU;
DROP TRIGGER if exists trig_01_refresh_GetAverageRatingByTrustedUser ON review;
DROP TRIGGER if exists trig_02_refresh_GetAverageRatingByTrustedUser ON trust;
DROP TRIGGER if exists trig_01_refresh_GetItemReviewsByTrustedUser ON review;
DROP TRIGGER if exists trig_02_refresh_GetItemReviewsByTrustedUser ON trust;
DROP TRIGGER if exists trig_01_refresh_GetReviewItemById ON review;
DROP TRIGGER if exists trig_02_refresh_GetReviewItemById ON item;
DROP TRIGGER if exists trig_01_refresh_GetReviewsByUser ON review;
DROP TRIGGER if exists trig_02_refresh_GetReviewsByUser ON "user";
drop materialized view if exists GetAverageRatingByTrustedUser;
drop materialized view if exists GetItemReviewsByTrustedUser;
drop materialized view if exists GetReviewItemById;
drop materialized view if exists GetReviewsByUser;
